-->> Skins.luau
-- Skins information in SM
--> Scripted by Marcos


local storage = game:GetService("ReplicatedStorage");
local bin = storage.Packages;
local _


local Skins = {
    ["Green Default"] = {
        Type = "Skin";
        Name = "Green Default";
        Image = 13275080504;
        Description = "Green edition of Default skin";
        Rarity = "Common";
    };
    ["Gladiator"] = {
        Type = "Skin";
        Name = "Gladiator";
        Image = 17173113068;
        Description = "This guy rules the Colosseum, for years no one took over his role as King of the Colosseum";
        Rarity = "Epic";
    };
    ["Molten Knight"] = {
        Type = "Skin";
        Name = "Molten Knight";
        Image = 91943337217989;
        Description = "A knight that came straight out from the lava";
        Rarity = "Exclusive";
    };
    ["Jake"] = {
        Type = "Skin";
        Name = "Jake";
        Image = 13275145431;
        Description = "A good friend of Bob";
        Rarity = "Uncommon";
    };
    ["K.O.S.S.O"] = {
        Type = "Skin";
        Name = "K.O.S.S.O";
        Image = 76960835627344;
        Description = "A robotic knight programmed to fight the evil";
        Rarity = "Rare";
    };
    ["Yellow Default"] = {
        Type = "Skin";
        Name = "Yellow Default";
        Image = 13275102846;
        Description = "Yellow edition of Default skin";
        Rarity = "Common";
    };
    ["Tom"] = {
        Type = "Skin";
        Name = "Tom";
        Image = 15645663791;
        Description = "An artist with a sword fighting skills";
        Rarity = "Uncommon";
    };
    ["Blue Default"] = {
        Type = "Skin";
        Name = "Blue Default";
        Image = 13275088193;
        Description = "Blue edition of Default skin";
        Rarity = "Common";
    };
    ["Void Crystal King"] = {
        Type = "Skin";
        Name = "Void Crystal King";
        Image = 89603376233486;
        Description = "Void version of Crystal King which is exclusive to players who complete special challenges";
        Rarity = "Exclusive";
    };
    ["Black Default"] = {
        Type = "Skin";
        Name = "Black Default";
        Image = 13275110830;
        Description = "Black edition of Default skin";
        Rarity = "Common";
    };
    ["Crystal King"] = {
        Type = "Skin";
        Name = "Crystal King";
        Image = 88883248982536;
        Description = "Ruler of the Crystal kingdom";
        Rarity = "Legendary";
    };
    ["Shadow Warrior"] = {
        Type = "Skin";
        Name = "Shadow Warrior";
        Image = 17072310877;
        Description = "A strange warrior from the unknown side of the space";
        Rarity = "Epic";
    };
    ["Default"] = {
        Type = "Skin";
        Name = "Default";
        Image = 13275067652;
        Description = "The starter skin of the game";
        Rarity = "Starter";
    };
    ["Red Default"] = {
        Type = "Skin";
        Name = "Red Default";
        Image = 13275095270;
        Description = "Red edition of Default skin";
        Rarity = "Common";
    };
    ["Bob"] = {
        Type = "Skin";
        Name = "Bob";
        Image = 13275158458;
        Description = "Some People see him as a cook, others see him as meme, but everyone knows he's Bob!";
        Rarity = "Rare";
    };
    ["Mountain Guardian"] = {
        Type = "Skin";
        Name = "Mountain Guardian";
        Image = 14113743972;
        Description = "This thing rules the mountain top. No one knows if he's evil or not, but he doesn't let anyone be on his mountain...";
        Rarity = "Special";
    };
    ["Noob"] = {
        Type = "Skin";
        Name = "Noob";
        Image = 13275117554;
        Description = "He is just a cute innocent noobie!";
        Rarity = "Uncommon";
    };
    ["Jack"] = {
        Type = "Skin";
        Name = "Jack";
        Image = 13275124115;
        Description = "Dude from the hood";
        Rarity = "Uncommon";
    };

};







return Skins;